services:
  backend:
    image: neksper/backend:v19-dev
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - backend_data:/data

  db:
    image: postgres:10
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  backend_data:
  redis_data:
  pgdata: