export interface miglioramentiInterface {
  id: number;
  name: string;
  description: string;
  cost: number;
  isInfinite: boolean;
  imagePath: string;
}

export const miglioramentiList: miglioramentiInterface[] = [
  {
    id: 1,
    name: "Таинственный мешок",
    description: "Мгновенно получаете 500 монет с вероятностью 50%.",
    cost: 2,
    // cost: 280,
    isInfinite: false,
    imagePath: "treasureBag.svg",
  },
  {
    id: 2,
    name: "Счастливый день",
    description: "Мгновенно получаете 1000 монет с вероятностью 25%",
    cost: 3,
    // cost: 300,
    isInfinite: false,
    imagePath: "luckyDay.svg",
  },
  {
    id: 3,
    name: "Клик удачи",
    description: "Следующий клик имеет 10% шанс принести 50 алмазов.",
    cost: 6,
    // cost: 600,
    isInfinite: false,
    imagePath: "happinesIcon.svg",
  },
  {
    id: 4,
    name: "Сундук сокровищ",
    description: "Мгновенно получаете от 300 до 1500 монет",
    cost: 10,
    // cost: 1000,
    isInfinite: false,
    imagePath: "chest.svg",
  },
  {
    id: 5,
    name: "Золотая лихорадка",
    description: "Следующие 50 кликов приносят в 2 раза больше монет.",
    cost: 15,
    // cost: 1500,
    isInfinite: false,
    imagePath: "gold.svg",
  },
  {
    id: 6,
    name: "Взрывные клики",
    description: "Следующие 5 кликов приносят 10x монет.",
    cost: 5,
    // cost: 500,
    isInfinite: false,
    imagePath: "bombClicks.svg",
  },
  {
    id: 7,
    name: "Магический артефакт",
    description:
      "Следующие 30 секунд каждый клик приносит в 3 раза больше монет.",
    cost: 7,
    // cost: 700,
    isInfinite: false,
    imagePath: "magicStick.svg",
  },
  {
    id: 8,
    name: "Улучшенный курсор",
    description: "Увеличивает доход с каждого клика на 1 монету.",
    cost: 5,
    // cost: 500,
    isInfinite: true,
    imagePath: "advancedCursor.svg",
  },
  {
    id: 9,
    name: "Золотая перчатка",
    description: "Увеличивает доход с каждого клика на 2 монеты.",
    cost: 10,
    // cost: 1000,
    isInfinite: true,
    imagePath: "goldGlove.svg",
  },
  {
    id: 10,
    name: "Магический курсор",
    description: "Увеличивает доход с каждого клика на 5 монет.",
    cost: 30,
    // cost: 3000,
    isInfinite: true,
    imagePath: "magicCursor.svg",
  },
  {
    id: 11,
    name: "Золотая фигурка",
    description: "Увеличивает доход с каждого клика на 10 монет.",
    cost: 7,
    // cost: 7000,
    isInfinite: true,
    imagePath: "goldFigure.svg",
  },
  {
    id: 12,
    name: "Легендарный курсор",
    description: "Увеличивает доход с каждого клика на 20 монет.",
    cost: 15,
    // cost: 15000,
    isInfinite: true,
    imagePath: "legendCursor.svg",
  },
  {
    id: 13,
    name: "Автокликер",
    description: "Добавляет 1 автоматический клик в секунду.",
    cost: 5,
    // cost: 5000,
    isInfinite: true,
    imagePath: "autoClicker.svg",
  },
  {
    id: 14,
    name: "Удвоитель дохода",
    description: "Все клики приносят в 2 раза больше монет.",
    cost: 10,
    // cost: 10000,
    isInfinite: true,
    imagePath: "x2.svg",
  },
  {
    id: 15,
    name: "Множитель дохода",
    description: "Все доходы (клики и автоклики) умножаются на 3.",
    cost: 5,
    // cost: 50000,
    isInfinite: true,
    imagePath: "x3.svg",
  },
];
