"""Added image_path field in Upgrade model

Revision ID: 46dc443bbe92
Revises: 65c786d8b8e2
Create Date: 2025-04-03 01:31:50.692265

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '46dc443bbe92'
down_revision = '65c786d8b8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upgrade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(), nullable=True))

    # Добавить запись в Upgrade
    from app.models import Upgrade
    from sqlalchemy.orm import Session

    bind = op.get_bind()
    session = Session(bind=bind)

    nickname_change = Upgrade(
        name="nickname_change",
        description="Allows changing your username",
        upgrade_type="consumable",
        effect_type="other",
        cost_coins=100,
    )

    session.add(nickname_change)
    session.commit()


    upgrades = [
        {
            'id': 1,
            'name': 'Таинственный мешок',
            'description': 'Мгновенно получаете 500 монет с вероятностью 50%.',
            'cost': 2,  # 'cost': 280,
            'isInfinite': False,
            'effect_type': 'income',
            'imagePath': 'treasureBag.svg',
        },
        {
            'id': 2,
            'name': 'Счастливый день',
            'description': 'Мгновенно получаете 1000 монет с вероятностью 25%',
            'cost': 3,  # 'cost': 300,
            'isInfinite': False,
            'effect_type': 'income',
            'imagePath': 'luckyDay.svg',
        },
        {
            'id': 3,
            'name': 'Клик удачи',
            'description': 'Следующий клик имеет 10% шанс принести 50 алмазов.',
            'cost': 6,  # 'cost': 600,
            'isInfinite': False,
            'effect_type': 'click',
            'imagePath': 'happinesIcon.svg',
        },
        {
            'id': 4,
            'name': 'Сундук сокровищ',
            'description': 'Мгновенно получаете от 300 до 1500 монет',
            'cost': 10,  # 'cost': 1000,
            'isInfinite': False,
            'effect_type': 'income',
            'imagePath': 'chest.svg',
        },
        {
            'id': 5,
            'name': 'Золотая лихорадка',
            'description': 'Следующие 50 кликов приносят в 2 раза больше монет.',
            'cost': 15,  # 'cost': 1500,
            'isInfinite': False,
            'effect_type': 'click',
            'imagePath': 'gold.svg',
        },
        {
            'id': 6,
            'name': 'Взрывные клики',
            'description': 'Следующие 5 кликов приносят 10x монет.',
            'cost': 5,  # 'cost': 500,
            'isInfinite': False,
            'effect_type': 'click',
            'imagePath': 'bombClicks.svg',
        },
        {
            'id': 7,
            'name': 'Магический артефакт',
            'description':
                'Следующие 30 секунд каждый клик приносит в 3 раза больше монет.',
            'cost': 7,  # 'cost': 700,
            'isInfinite': False,
            'effect_type': 'click',
            'imagePath': 'magicStick.svg',
        },
        {
            'id': 8,
            'name': 'Улучшенный курсор',
            'description': 'Увеличивает доход с каждого клика на 1 монету.',
            'cost': 5,  # 'cost': 500,
            'isInfinite': True,
            'effect_type': 'click',
            'imagePath': 'advancedCursor.svg',
        },
        {
            'id': 9,
            'name': 'Золотая перчатка',
            'description': 'Увеличивает доход с каждого клика на 2 монеты.',
            'cost': 10,  # 'cost': 1000,
            'isInfinite': True,
            'effect_type': 'click',
            'imagePath': 'goldGlove.svg',
        },
        {
            'id': 10,
            'name': 'Магический курсор',
            'description': 'Увеличивает доход с каждого клика на 5 монет.',
            'cost': 30,  # 'cost': 3000,
            'isInfinite': True,
            'effect_type': 'click',
            'imagePath': 'magicCursor.svg',
        },
        {
            'id': 11,
            'name': 'Золотая фигурка',
            'description': 'Увеличивает доход с каждого клика на 10 монет.',
            'cost': 7,  # 'cost': 7000,
            'isInfinite': True,
            'effect_type': 'click',
            'imagePath': 'goldFigure.svg',
        },
        {
            'id': 12,
            'name': 'Легендарный курсор',
            'description': 'Увеличивает доход с каждого клика на 20 монет.',
            'cost': 15,  # 'cost': 15000,
            'isInfinite': True,
            'effect_type': 'click',
            'imagePath': 'legendCursor.svg',
        },
        {
            'id': 13,
            'name': 'Автокликер',
            'description': 'Добавляет 1 автоматический клик в секунду.',
            'cost': 5,  # 'cost': 5000, 
            'isInfinite': True,
            'effect_type': 'click',
            'imagePath': 'autoClicker.svg',
        },
        {
            'id': 14,
            'name': 'Удвоитель дохода',
            'description': 'Все клики приносят в 2 раза больше монет.',
            'cost': 10,  # 'cost': 10000,
            'isInfinite': True,
            'effect_type': 'click',
            'imagePath': 'x2.svg',
        },
        {
            'id': 15,
            'name': 'Множитель дохода',
            'description': 'Все доходы (клики и автоклики) умножаются на 3.',
            'cost': 5,  # 'cost': 50000,
            'isInfinite': True,
            'effect_type': 'click',
            'imagePath': 'x3.svg',
        },
    ]

    bind = op.get_bind()
    session = Session(bind=bind)

    for upgrade in upgrades:
        session.add(Upgrade(name=upgrade['name'], description=upgrade['description'], cost_coins=upgrade['cost'],
                            upgrade_type='permanent' if upgrade['isInfinite'] else 'consumable',
                            effect_type=upgrade['effect_type'], image_path=upgrade['imagePath']))
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    op.execute("DELETE FROM upgrade")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upgrade', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
