"""Added Upgrade and UserUpgrade models

Revision ID: 49cfe7b05432
Revises: c4189beafafe
Create Date: 2025-03-03 20:40:09.208617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cfe7b05432'
down_revision = 'c4189beafafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upgrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('upgrade_type', sa.Enum('consumable', 'permanent', name='upgrade_type'), nullable=False),
    sa.Column('effect_type', sa.Enum('click', 'income', 'other', name='effect_type'), nullable=False),
    sa.Column('cost_coins', sa.Integer(), nullable=False),
    sa.Column('cost_diamonds', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_upgrade',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upgrade_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['upgrade_id'], ['upgrade.id'], name='fk_userupgrade_upgrade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_userupgrade_user'),
    sa.PrimaryKeyConstraint('user_id', 'upgrade_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('diamonds', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('base_per_click', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('base_per_minute', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_update')
        batch_op.drop_column('base_per_minute')
        batch_op.drop_column('base_per_click')
        batch_op.drop_column('diamonds')
        batch_op.drop_column('coins')

    op.drop_table('user_upgrade')
    op.drop_table('upgrade')
    # ### end Alembic commands ###
