"""Added index in Upgrade and Container image_path filed

Revision ID: 57164b1948d9
Revises: cb362e561c68
Create Date: 2025-04-20 12:16:11.775824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57164b1948d9'
down_revision = 'cb362e561c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_image_path'), ['image_path'], unique=False)

    with op.batch_alter_table('upgrade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upgrade_image_path'), ['image_path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upgrade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upgrade_image_path'))

    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_image_path'))

    # ### end Alembic commands ###
