"""Feat: Container model with ContainerReward model and UserContainer model for many-to-many relationship

Revision ID: 837befb80f49
Revises: fd32018c7a99
Create Date: 2025-04-13 12:58:23.468181

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '837befb80f49'
down_revision = 'fd32018c7a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('image_path', sa.String(), nullable=False),
                    sa.Column('cost_coins', sa.Integer(), nullable=False),
                    sa.Column('cost_diamonds', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('container_reward',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('container_id', sa.Integer(), nullable=False),
                    sa.Column('coins', sa.Integer(), nullable=True),
                    sa.Column('diamonds', sa.Integer(), nullable=True),
                    sa.Column('fk_upgrade_container', sa.Integer(), nullable=True),
                    sa.Column('fk_awardedcontainer_container', sa.Integer(), nullable=True),
                    sa.Column('count', sa.Integer(), nullable=False),
                    sa.Column('image_path', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['container_id'], ['container.id'], name='fk_containerreward_container'),
                    sa.ForeignKeyConstraint(['fk_awardedcontainer_container'], ['container.id'], ),
                    sa.ForeignKeyConstraint(['fk_upgrade_container'], ['upgrade.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_container',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('container_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['container_id'], ['container.id'], name='fk_usercontainer_container'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_usercontainer_user'),
                    sa.PrimaryKeyConstraint('user_id', 'container_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_container')
    op.drop_table('container_reward')
    op.drop_table('container')
    # ### end Alembic commands ###
