"""Feat: Container model with ContainerReward model and UserContainer model for many-to-many relationship

Revision ID: 837befb80f49
Revises: fd32018c7a99
Create Date: 2025-04-13 12:58:23.468181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837befb80f49'
down_revision = 'fd32018c7a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('price_coins', sa.Integer(), nullable=False),
    sa.Column('price_diamonds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('container_reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('diamonds', sa.Integer(), nullable=True),
    sa.Column('fk_upgrade_container', sa.Integer(), nullable=True),
    sa.Column('fk_awardedcontainer_container', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], name='fk_containerreward_container'),
    sa.ForeignKeyConstraint(['fk_awardedcontainer_container'], ['container.id'], ),
    sa.ForeignKeyConstraint(['fk_upgrade_container'], ['upgrade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_container',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], name='fk_usercontainer_container'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_usercontainer_user'),
    sa.PrimaryKeyConstraint('user_id', 'container_id')
    )
    # ### end Alembic commands ###

    from app.models import Container, ContainerReward
    from sqlalchemy.orm import Session

    session = Session(bind=op.get_bind())
    container_list = [
        {
            "name": "Простой",
            "imagePath": "container-simple.png",
            "price": {"coins": 500, "diamonds": 3},
            "rewards": [
                {"coins": 50},
                {"coins": 100},
                {"coins": 200},
                {"coins": 300},
                {"coins": 400},
                {"coins": 500},
                {"coins": 750},
                {"coins": 1000},
                {"coins": 1500},
                {"coins": 3000},
                {"coins": 5000},
                {"improvement_id": 1, "imagePath": "miglioramenti/treasureBag.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "miglioramenti/chest.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "miglioramenti/luckyDay.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "miglioramenti/magicStick.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "miglioramenti/bombClicks.svg", "count": 1},
                {"diamonds": 1},
                {"diamonds": 3},
                {"diamonds": 5},
                {"container_id": 1, "imagePath": "containers/container-simple.png", "count": 1},
            ],
        },
        {
            "name": "Редкий",
            "imagePath": "container-rare.png",
            "price": {"coins": 1500, "diamonds": 10},
            "rewards": [
                {"coins": 200},
                {"coins": 400},
                {"coins": 600},
                {"coins": 800},
                {"coins": 1000},
                {"coins": 1500},
                {"coins": 2000},
                {"coins": 5000},
                {"coins": 8000},
                {"improvement_id": 1, "imagePath": "treasureBag.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "happinesIcon.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "gold.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "magicStick.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "bombClicks.svg", "count": 1},
                {"diamonds": 3},
                {"diamonds": 10},
                {"diamonds": 15},
                {"container_id": 1, "imagePath": "containers/container-simple.png", "count": 1},
                {"container_id": 1, "imagePath": "containers/container-simple.png", "count": 2},
                {"container_id": 1, "imagePath": "containers/container-rare.png", "count": 1},
            ],
        },
        {
            "name": "Эпический",
            "imagePath": "container-epic.png",
            "price": {
                "coins": 5000,
                "diamonds": 30,
            },
            "rewards": [
                {"coins": 500},
                {"coins": 750},
                {"coins": 1000},
                {"coins": 1500},
                {"coins": 4000},
                {"coins": 6000},
                {"coins": 10000},
                {"improvement_id": 1, "imagePath": "bombClicks.svg", "count": 3},
                {"improvement_id": 1, "imagePath": "happinesIcon.svg", "count": 4},
                {"improvement_id": 1, "imagePath": "treasureBag.svg", "count": 5},
                {"improvement_id": 1, "imagePath": "gold.svg", "count": 3},
                {"improvement_id": 1, "imagePath": "advancedCursor.svg", "count": 1},
                {"diamonds": 10},
                {"diamonds": 20},
                {"diamonds": 50},
                {"diamonds": 80},
                {"container_id": 1, "imagePath": "containers/container-simple.png", "count": 3},
                {"container_id": 1, "imagePath": "containers/container-simple.png", "count": 4},
                {"container_id": 1, "imagePath": "containers/container-rare.png", "count": 2},
                {"container_id": 1, "imagePath": "containers/container-epic.png", "count": 1},
            ],
        },
        {
            "name": "Мифический",
            "imagePath": "container-mythical.png",
            "price": {
                "coins": 20000,
                "diamonds": 150,
            },
            "rewards": [
                {"coins": 1000},
                {"coins": 5000},
                {"coins": 7500},
                {"coins": 10000},
                {"coins": 15000},
                {"coins": 20000},
                {"coins": 30000},
                {"coins": 40000},
                {"improvement_id": 1, "count": 10, "imagePath": "happinesIcon.svg"},
                {"improvement_id": 1, "imagePath": "treasureBag.svg", "count": 15},
                {"improvement_id": 1, "imagePath": "magicCursor.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "advancedCursor.svg", "count": 1},
                {"diamonds": 30},
                {"diamonds": 50},
                {"diamonds": 80},
                {"diamonds": 150},
                {"container_id": 1, "imagePath": "containers/container-simple.png", "count": 10},
                {"container_id": 1, "imagePath": "containers/container-rare.png", "count": 5},
                {"container_id": 1, "imagePath": "containers/container-epic.png", "count": 3},
                {"container_id": 1, "imagePath": "containers/container-mythical.png", "count": 1},
            ],
        },
        {
            "name": "Легендарный",
            "imagePath": "container-legendary.png",
            "price": {
                "coins": 80000,
                "diamonds": 600,
            },
            "rewards": [
                {"coins": 10000},
                {"coins": 30000},
                {"coins": 50000},
                {"coins": 70000},
                {"coins": 100000},
                {"coins": 150000},
                {"coins": 200000},
                {"coins": 0},
                {"improvement_id": 1, "imagePath": "autoClicker.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "x2.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "magicCursor.svg", "count": 1},
                {"improvement_id": 1, "imagePath": "advancedCursor.svg", "count": 1},
                {"diamonds": 100},
                {"diamonds": 300},
                {"diamonds": 500},
                {"diamonds": 600},
                {"container_id": 1, "imagePath": "containers/container-rare.png", "count": 10},
                {"container_id": 1, "imagePath": "containers/container-epic.png", "count": 5},
                {"container_id": 1, "imagePath": "containers/container-mythical.png", "count": 3},
                {"container_id": 1, "imagePath": "containers/container-legendary.png", "count": 1},
            ],
        }
    ]

    for container in container_list:
        container_row = Container(
            name=container['name'],
            image_path=container['imagePath'],
            price_coins=container['price']['coins'],
            price_diamonds=container['price']['diamonds']
        )
        session.add(container_row)
        session.flush()

        for reward in container['rewards']:
            reward_data = {
                'container_id': container_row.id,
                'coins': reward.get('coins'),
                'diamonds': reward.get('diamonds'),
                'improvement_id': reward.get('improvement_id'),
                "awarded_container_id": reward.get("container_id"),
                "image_path": reward.get("imagePath", ""),
                "count": reward.get("count", 1),
            }
            container_reward_row = ContainerReward(**reward_data)
            session.add(container_reward_row)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_container')
    op.drop_table('container_reward')
    op.drop_table('container')
    # ### end Alembic commands ###
