"""Added changes_number and keys fields in User model

Revision ID: 890f1d98f160
Revises: 57164b1948d9
Create Date: 2025-04-28 18:24:24.875076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890f1d98f160'
down_revision = '57164b1948d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changes_number', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('keys', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('keys')
        batch_op.drop_column('changes_number')

    # ### end Alembic commands ###
