"""Feat: added current_reward_day and last_reward_claimed_at so that the user can receive DailyReward

Revision ID: d5057322f793
Revises: 837befb80f49
Create Date: 2025-04-15 23:33:10.428492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5057322f793'
down_revision = '837befb80f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_reward_day', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_reward_claimed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_reward_claimed_at')
        batch_op.drop_column('current_reward_day')

    # ### end Alembic commands ###
