"""Added DailyReward model

Revision ID: fd32018c7a99
Revises: 46dc443bbe92
Create Date: 2025-04-03 01:35:10.525226

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fd32018c7a99'
down_revision = '46dc443bbe92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reward',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('coins', sa.Integer(), nullable=True),
                    sa.Column('diamonds', sa.Integer(), nullable=True),
                    sa.Column('custom', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    from app.models import DailyReward
    from sqlalchemy.orm import Session

    bind = op.get_bind()
    session = Session(bind=bind)

    daily_rewards_list = [
        {'id': 1, 'rewards': {'coins': 50}},
        {'id': 2, 'rewards': {'diamonds': 1}},
        {'id': 3, 'rewards': {'coins': 100}},
        {'id': 4, 'rewards': {'diamonds': 5}},
        {'id': 5, 'rewards': {'custom': "/miglioramenti/chest.svg"}},
        {'id': 6, 'rewards': {'coins': 200}},
        {'id': 7, 'rewards': {'custom': "/miglioramenti/gold.svg"}},
        {'id': 8, 'rewards': {'diamonds': 10}},
        {'id': 9, 'rewards': {'custom': "/miglioramenti/bombClicks.svg"}},
        {'id': 10, 'rewards': {'custom': "/containers/container-simple.png"}},
        {'id': 11, 'rewards': {'custom': "/miglioramenti/happinesIcon.svg"}},
        {'id': 12, 'rewards': {'coins': 500}},
        {'id': 13, 'rewards': {'custom': "/containers/container-rare.png"}},
        {'id': 14, 'rewards': {'diamonds': 20}},
    ]

    for reward in daily_rewards_list:
        if 'coins' in reward['rewards']:
            session.add(DailyReward(coins=reward['rewards']['coins']))
        elif 'diamonds' in reward['rewards']:
            session.add(DailyReward(diamonds=reward['rewards']['diamonds']))
        elif 'custom' in reward['rewards']:
            session.add(DailyReward(custom=reward['rewards']['custom']))
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_reward')
    # ### end Alembic commands ###
